#!/bin/bash

HEAP_SIZE=1024m
GC_STRATEGY="-XX:+UseParallelGC -XX:+UseParallelOldGC" # High throughput, but could have long GC pauses
java -Xverify:none -XX:MaxPermSize=128m -Xms$HEAP_SIZE -Xmx$HEAP_SIZE -Xss2M -XX:+UseTLAB $GC_STRATEGY -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -jar `dirname $0`/sbt-launch.jar "$@"
